_wandb:
    value:
        cli_version: 0.28.1
        e:
            uxts9v6vlwnlf2p0uaamqoll6lfa5nv9:
                codePath: run_sweep.py
                codePathLocal: run_sweep.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "234039422976"
                        used: "76599209984"
                email: pieromutasci@gmail.com
                executable: /usr/bin/python3
                host: 00ee6c3c2183
                memory:
                    total: "7511293952"
                os: Linux-7.0.0-28-generic-x86_64-with-glibc2.35
                program: /home/user/ros_workspace/wandb/./run_sweep.py
                python: CPython 3.10.12
                root: /home/user/ros_workspace/wandb
                startedAt: "2026-07-27T09:30:37.458677Z"
                writerId: uxts9v6vlwnlf2p0uaamqoll6lfa5nv9
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 14
            "4": 3.10.12
            "5": 0.28.1
            "12": 0.28.1
            "13": linux-x86_64
box_gain:
    value: 6.727973183487745
cls_gain:
    value: 0.6310518730341383
copy_paste:
    value: 0.22391814590647077
dfl_gain:
    value: 1.5446293786475251
imgsz:
    value: 640
lr0:
    value: 0.0011946554404082398
lrf:
    value: 0.032976061459519715
momentum:
    value: 0.8920482601925039
mosaic:
    value: 0.6911371073233462
optimizer:
    value: AdamW
scale:
    value: 0.09477201613542556
translate:
    value: 0.1420962307447321
weight_decay:
    value: 0.00010451146691224474
