_wandb:
    value:
        cli_version: 0.28.1
        e:
            8bygbfq2ygifztr4p67errffzelhenxo:
                args:
                    - --sweep-id
                    - sqkfh2ka
                codePath: run_sweep.py
                codePathLocal: run_sweep.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "234039422976"
                        used: "79658364928"
                email: pieromutasci@gmail.com
                executable: /usr/bin/python3
                host: 5579395e9134
                memory:
                    total: "7511289856"
                os: Linux-7.0.0-28-generic-x86_64-with-glibc2.35
                program: /home/user/ros_workspace/wandb/./run_sweep.py
                python: CPython 3.10.12
                root: /home/user/ros_workspace/wandb
                startedAt: "2026-07-30T06:54:10.772276Z"
                writerId: 8bygbfq2ygifztr4p67errffzelhenxo
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 14
            "4": 3.10.12
            "5": 0.28.1
            "12": 0.28.1
            "13": linux-x86_64
box_gain:
    value: 6.679360343295507
cls_gain:
    value: 0.516110583366607
copy_paste:
    value: 0.2802954911288572
dfl_gain:
    value: 1.4935337408512288
imgsz:
    value: 640
lr0:
    value: 0.002652314686574803
lrf:
    value: 0.12789718942608613
momentum:
    value: 0.8567943777612007
mosaic:
    value: 0.987196401708934
optimizer:
    value: AdamW
scale:
    value: 0.07724421731830955
translate:
    value: 0.025696338187788516
weight_decay:
    value: 0.0002713954530677134
