_wandb:
    value:
        cli_version: 0.28.1
        e:
            oybhrwzxps5ne74suenih5ej8k6x13f1:
                args:
                    - --sweep-id
                    - sqkfh2ka
                codePath: run_sweep.py
                codePathLocal: run_sweep.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "234039422976"
                        used: "79677259776"
                email: pieromutasci@gmail.com
                executable: /usr/bin/python3
                host: 9b264fcab671
                memory:
                    total: "7511285760"
                os: Linux-7.0.0-28-generic-x86_64-with-glibc2.35
                program: /home/user/ros_workspace/wandb/./run_sweep.py
                python: CPython 3.10.12
                root: /home/user/ros_workspace/wandb
                startedAt: "2026-07-30T09:57:09.218875Z"
                writerId: oybhrwzxps5ne74suenih5ej8k6x13f1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 14
            "4": 3.10.12
            "5": 0.28.1
            "12": 0.28.1
            "13": linux-x86_64
box_gain:
    value: 7.756046327520125
cls_gain:
    value: 0.39784362106652593
copy_paste:
    value: 0.018813534211737825
dfl_gain:
    value: 1.4202045694299723
imgsz:
    value: 640
lr0:
    value: 0.0020861978195133592
lrf:
    value: 0.14671715140285818
momentum:
    value: 0.9472826986240824
mosaic:
    value: 0.6754329225148199
optimizer:
    value: AdamW
scale:
    value: 0.009480674445028203
translate:
    value: 0.07773759785554063
weight_decay:
    value: 0.0006272441531628927
