_wandb:
    value:
        cli_version: 0.28.1
        e:
            dpbukl9x9p3r6f4uiea0iafpf1gzzpbr:
                args:
                    - --sweep-id
                    - sqkfh2ka
                codePath: run_sweep.py
                codePathLocal: run_sweep.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "234039422976"
                        used: "79095283712"
                email: pieromutasci@gmail.com
                executable: /usr/bin/python3
                host: 5579395e9134
                memory:
                    total: "7511289856"
                os: Linux-7.0.0-28-generic-x86_64-with-glibc2.35
                program: /home/user/ros_workspace/wandb/./run_sweep.py
                python: CPython 3.10.12
                root: /home/user/ros_workspace/wandb
                startedAt: "2026-07-29T18:57:41.345806Z"
                writerId: dpbukl9x9p3r6f4uiea0iafpf1gzzpbr
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 14
            "4": 3.10.12
            "5": 0.28.1
            "12": 0.28.1
            "13": linux-x86_64
box_gain:
    value: 8.559434620243891
cls_gain:
    value: 0.5392083470413094
copy_paste:
    value: 0.2246237512323295
dfl_gain:
    value: 1.5242612136589218
imgsz:
    value: 640
lr0:
    value: 0.001484459229951018
lrf:
    value: 0.015236662302553406
momentum:
    value: 0.9755006268085632
mosaic:
    value: 0.8311312804711657
optimizer:
    value: AdamW
scale:
    value: 0.12254412705630148
translate:
    value: 0.06455244943216183
weight_decay:
    value: 0.00011759029359338114
