_wandb:
    value:
        cli_version: 0.28.1
        e:
            qoc5az6n1g3izc176pyi0z1w8du8zxaj:
                args:
                    - --sweep-id
                    - sqkfh2ka
                codePath: run_sweep.py
                codePathLocal: run_sweep.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "234039422976"
                        used: "77509316608"
                email: pieromutasci@gmail.com
                executable: /usr/bin/python3
                host: 7d1123c7997c
                memory:
                    total: "7511293952"
                os: Linux-7.0.0-28-generic-x86_64-with-glibc2.35
                program: /home/user/ros_workspace/wandb/run_sweep.py
                python: CPython 3.10.12
                root: /home/user/ros_workspace/wandb
                startedAt: "2026-07-28T00:04:20.805723Z"
                writerId: qoc5az6n1g3izc176pyi0z1w8du8zxaj
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 14
            "4": 3.10.12
            "5": 0.28.1
            "12": 0.28.1
            "13": linux-x86_64
box_gain:
    value: 8.60908607591503
cls_gain:
    value: 0.6311956534028079
copy_paste:
    value: 0.04800224649525007
dfl_gain:
    value: 1.6829748968489506
imgsz:
    value: 640
lr0:
    value: 0.0011907576599183513
lrf:
    value: 0.130270442707296
momentum:
    value: 0.8852888625880246
mosaic:
    value: 0.8376309402947161
optimizer:
    value: SGD
scale:
    value: 0.0673654444517574
translate:
    value: 0.1918714480467729
weight_decay:
    value: 0.00019399473703876833
